version: '3.8'

services:
  postgresql:
    image: pgvector/pgvector:pg16
    container_name: lobe-postgres
    ports:
      - '5433:5433'
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}  # Utilisation des variables d'environnement depuis Coolify
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  # Utilisation du mot de passe PostgreSQL défini dans Coolify
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  minio:
    image: minio/minio
    container_name: lobe-minio
    ports:
      - '9000:9000'  # API MinIO
      - '9001:9001'  # Console MinIO
    volumes:
      - /srv/minio/data:/etc/minio/data  # Volume pour persister les données
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}  # Utilisation des variables d'environnement depuis Coolify
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DOMAIN=${MINIO_DOMAIN}
      - MINIO_API_CORS_ALLOW_ORIGIN=${MINIO_API_CORS_ALLOW_ORIGIN}
    restart: always
    command: >
      server /etc/minio/data --address ":9000" --console-address ":9001"

  logto:
    image: svhd/logto
    container_name: lobe-logto
    ports:
      - '3001:3001'
      - '3002:3002'
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - 'TRUST_PROXY_HEADER=1'
      - 'DB_URL=postgresql://postgres:uWNZugjBqixf8dxC@postgresql:5432/logto'
      - 'ENDPOINT=https://lobe-auth-api.example.com'
      - 'ADMIN_ENDPOINT=https://lobe-auth-ui.example.com'
    entrypoint: ['sh', '-c', 'npm run cli db seed -- --swe && npm start']



  lobe:
    image: lobehub/lobe-chat-database
    container_name: lobe-database
    ports:
      - '3210:3210'
    depends_on:
      - postgresql
      - minio
    environment:
      - DB_URL=${DATABASE_URL}  # Connexion à PostgreSQL via la variable d'environnement dans Coolify
      - MINIO_URL=${MINIOS3_API_URL}  # Utilisation de l'URL API MinIO depuis Coolify
    restart: always

volumes:
  data:
    driver: local
  minio_data:
    driver: local
  s3_data:
    driver: local
